// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"encoding/json"
)

type Transaction struct {
	ID        int64
	Uri       string
	ProgramID string
	Data      json.RawMessage
}
