// Code generated by narsilc. DO NOT EDIT.
// source: query.sql

package queries

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/mbvlabs/narsilc"
)

const listActiveUsers = `-- name: ListActiveUsers :many
WITH u AS (
  SELECT id, email FROM users
)
SELECT id, email FROM u
`

type ListActiveUsersRow struct {
	ID    int64  `andurel:"id"`
	Email string `andurel:"email"`
}

func (q *Queries) ListActiveUsers[T any](ctx context.Context) *ListActiveUsersBuilder[T] {
	return &ListActiveUsersBuilder[T]{
		q:        q,
		ctx:      ctx,
		args:     []any{},
		hasWhere: false,
		dollar:   true,
	}
}

type ListActiveUsersBuilder[T any] struct {
	q        *Queries
	ctx      context.Context
	args     []any
	conds    []string
	order    string
	limit    *int32
	offset   *int32
	hasWhere bool
	dollar   bool
}

func (b *ListActiveUsersBuilder[T]) OrderByUIDAsc() *ListActiveUsersBuilder[T] {
	b.order = `u.id ASC`
	return b
}

func (b *ListActiveUsersBuilder[T]) OrderByUIDDesc() *ListActiveUsersBuilder[T] {
	b.order = `u.id DESC`
	return b
}

func (b *ListActiveUsersBuilder[T]) Limit(n int32) *ListActiveUsersBuilder[T] {
	b.limit = &n
	return b
}

func (b *ListActiveUsersBuilder[T]) Offset(n int32) *ListActiveUsersBuilder[T] {
	b.offset = &n
	return b
}

func (b *ListActiveUsersBuilder[T]) build() string {
	query := listActiveUsers
	if len(b.conds) > 0 {
		if b.hasWhere {
			query += " AND " + strings.Join(b.conds, " AND ")
		} else {
			query += " WHERE " + strings.Join(b.conds, " AND ")
		}
	}
	if b.order != "" {
		query += " ORDER BY " + b.order
	}
	if b.limit != nil {
		b.args = append(b.args, *b.limit)
		if b.dollar {
			query += fmt.Sprintf(" LIMIT $%d", len(b.args))
		} else {
			query += " LIMIT ?"
		}
	}
	if b.offset != nil {
		b.args = append(b.args, *b.offset)
		if b.dollar {
			query += fmt.Sprintf(" OFFSET $%d", len(b.args))
		} else {
			query += " OFFSET ?"
		}
	}
	return query
}

func (b *ListActiveUsersBuilder[T]) All() ([]T, error) {
	query := b.build()
	rows, err := b.q.db.Query(b.ctx, query, b.args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	var probe T
	_, mapRow := any(&probe).(narsilc.Transformer[ListActiveUsersRow])
	cols := []string{"id", "email"}
	for rows.Next() {
		var item T
		var err error
		if mapRow {
			var scanned ListActiveUsersRow
			scanned, err = narsilc.Scan[ListActiveUsersRow](rows, cols)
			if err == nil {
				item, err = narsilc.FromRow[T, ListActiveUsersRow](scanned)
			}
		} else {
			item, err = narsilc.Scan[T](rows, cols)
		}
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTokens = `-- name: ListUserTokens :many
SELECT u.id, u.email, t.id, t.scope
FROM users u
JOIN tokens t ON t.user_id = u.id
`

type ListUserTokensRow struct {
	ID    int64       `andurel:"id"`
	Email string      `andurel:"email"`
	ID_2  pgtype.UUID `andurel:"id"`
	Scope string      `andurel:"scope"`
}

func (q *Queries) ListUserTokens[T any](ctx context.Context) *ListUserTokensBuilder[T] {
	return &ListUserTokensBuilder[T]{
		q:        q,
		ctx:      ctx,
		args:     []any{},
		hasWhere: false,
		dollar:   true,
	}
}

type ListUserTokensBuilder[T any] struct {
	q        *Queries
	ctx      context.Context
	args     []any
	conds    []string
	order    string
	limit    *int32
	offset   *int32
	hasWhere bool
	dollar   bool
}

func (b *ListUserTokensBuilder[T]) UIDEq(v int64) *ListUserTokensBuilder[T] {
	b.args = append(b.args, v)
	b.conds = append(b.conds, fmt.Sprintf(`u.id = $%d`, len(b.args)))
	return b
}

func (b *ListUserTokensBuilder[T]) TIDEq(v pgtype.UUID) *ListUserTokensBuilder[T] {
	b.args = append(b.args, v)
	b.conds = append(b.conds, fmt.Sprintf(`t.id = $%d`, len(b.args)))
	return b
}

func (b *ListUserTokensBuilder[T]) ScopeEq(v string) *ListUserTokensBuilder[T] {
	b.args = append(b.args, v)
	b.conds = append(b.conds, fmt.Sprintf(`scope = $%d`, len(b.args)))
	return b
}

func (b *ListUserTokensBuilder[T]) OrderByUIDAsc() *ListUserTokensBuilder[T] {
	b.order = `u.id ASC`
	return b
}

func (b *ListUserTokensBuilder[T]) OrderByUIDDesc() *ListUserTokensBuilder[T] {
	b.order = `u.id DESC`
	return b
}

func (b *ListUserTokensBuilder[T]) OrderByTIDAsc() *ListUserTokensBuilder[T] {
	b.order = `t.id ASC`
	return b
}

func (b *ListUserTokensBuilder[T]) OrderByTIDDesc() *ListUserTokensBuilder[T] {
	b.order = `t.id DESC`
	return b
}

func (b *ListUserTokensBuilder[T]) OrderByScopeAsc() *ListUserTokensBuilder[T] {
	b.order = `scope ASC`
	return b
}

func (b *ListUserTokensBuilder[T]) OrderByScopeDesc() *ListUserTokensBuilder[T] {
	b.order = `scope DESC`
	return b
}

func (b *ListUserTokensBuilder[T]) Limit(n int32) *ListUserTokensBuilder[T] {
	b.limit = &n
	return b
}

func (b *ListUserTokensBuilder[T]) Offset(n int32) *ListUserTokensBuilder[T] {
	b.offset = &n
	return b
}

func (b *ListUserTokensBuilder[T]) build() string {
	query := listUserTokens
	if len(b.conds) > 0 {
		if b.hasWhere {
			query += " AND " + strings.Join(b.conds, " AND ")
		} else {
			query += " WHERE " + strings.Join(b.conds, " AND ")
		}
	}
	if b.order != "" {
		query += " ORDER BY " + b.order
	}
	if b.limit != nil {
		b.args = append(b.args, *b.limit)
		if b.dollar {
			query += fmt.Sprintf(" LIMIT $%d", len(b.args))
		} else {
			query += " LIMIT ?"
		}
	}
	if b.offset != nil {
		b.args = append(b.args, *b.offset)
		if b.dollar {
			query += fmt.Sprintf(" OFFSET $%d", len(b.args))
		} else {
			query += " OFFSET ?"
		}
	}
	return query
}

func (b *ListUserTokensBuilder[T]) All() ([]T, error) {
	query := b.build()
	rows, err := b.q.db.Query(b.ctx, query, b.args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	var probe T
	_, mapRow := any(&probe).(narsilc.Transformer[ListUserTokensRow])
	cols := []string{"id", "email", "id", "scope"}
	for rows.Next() {
		var item T
		var err error
		if mapRow {
			var scanned ListUserTokensRow
			scanned, err = narsilc.Scan[ListUserTokensRow](rows, cols)
			if err == nil {
				item, err = narsilc.FromRow[T, ListUserTokensRow](scanned)
			}
		} else {
			item, err = narsilc.Scan[T](rows, cols)
		}
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email FROM users
`

type ListUsersRow struct {
	ID    int64  `andurel:"id"`
	Email string `andurel:"email"`
}

func (q *Queries) ListUsers[T any](ctx context.Context) *ListUsersBuilder[T] {
	return &ListUsersBuilder[T]{
		q:        q,
		ctx:      ctx,
		args:     []any{},
		hasWhere: false,
		dollar:   true,
	}
}

type ListUsersBuilder[T any] struct {
	q        *Queries
	ctx      context.Context
	args     []any
	conds    []string
	order    string
	limit    *int32
	offset   *int32
	hasWhere bool
	dollar   bool
}

func (b *ListUsersBuilder[T]) OrderByPublicUsersIDAsc() *ListUsersBuilder[T] {
	b.order = `public.users.id ASC`
	return b
}

func (b *ListUsersBuilder[T]) OrderByPublicUsersIDDesc() *ListUsersBuilder[T] {
	b.order = `public.users.id DESC`
	return b
}

func (b *ListUsersBuilder[T]) Limit(n int32) *ListUsersBuilder[T] {
	b.limit = &n
	return b
}

func (b *ListUsersBuilder[T]) Offset(n int32) *ListUsersBuilder[T] {
	b.offset = &n
	return b
}

func (b *ListUsersBuilder[T]) build() string {
	query := listUsers
	if len(b.conds) > 0 {
		if b.hasWhere {
			query += " AND " + strings.Join(b.conds, " AND ")
		} else {
			query += " WHERE " + strings.Join(b.conds, " AND ")
		}
	}
	if b.order != "" {
		query += " ORDER BY " + b.order
	}
	if b.limit != nil {
		b.args = append(b.args, *b.limit)
		if b.dollar {
			query += fmt.Sprintf(" LIMIT $%d", len(b.args))
		} else {
			query += " LIMIT ?"
		}
	}
	if b.offset != nil {
		b.args = append(b.args, *b.offset)
		if b.dollar {
			query += fmt.Sprintf(" OFFSET $%d", len(b.args))
		} else {
			query += " OFFSET ?"
		}
	}
	return query
}

func (b *ListUsersBuilder[T]) All() ([]T, error) {
	query := b.build()
	rows, err := b.q.db.Query(b.ctx, query, b.args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	var probe T
	_, mapRow := any(&probe).(narsilc.Transformer[ListUsersRow])
	cols := []string{"id", "email"}
	for rows.Next() {
		var item T
		var err error
		if mapRow {
			var scanned ListUsersRow
			scanned, err = narsilc.Scan[ListUsersRow](rows, cols)
			if err == nil {
				item, err = narsilc.FromRow[T, ListUsersRow](scanned)
			}
		} else {
			item, err = narsilc.Scan[T](rows, cols)
		}
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
