// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
)

type Arena struct {
	Name sql.NullString
}

type Location struct {
	Name sql.NullString
}
