// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const refresh = `-- name: Refresh :exec
REFRESH MATERIALIZED VIEW myview
`

func (q *Queries) Refresh(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refresh)
	return err
}
