// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

type Location struct {
	ID        int64
	Name      string
	Address   string
	ZipCode   int64
	Latitude  float64
	Longitude float64
}
