// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID      int64
	Name    string
	Manager pgtype.Text
}
