// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package override

import (
	t "github.com/jackc/pgtype"
)

type Foo struct {
	Other   string
	Total   int64
	Retyped *t.Text
}
