version: 2

project_name: narsilc

builds:
  - id: narsilc
    main: ./cmd/narsilc
    binary: narsilc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/mbvlabs/narsilc/internal/cmd.version={{ .Tag }}

archives:
  - id: archives
    ids:
      - narsilc
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

snapshot:
  version_template: "nightly-{{ .Now.Format \"20060102\" }}-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  draft: false
  prerelease: auto
