// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
)

type Bar struct {
	ID int64
}

type Foo struct {
	ID  int64
	Bar sql.NullInt64
}
