// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
)

type Bar struct {
	A sql.NullString
	B sql.NullString
}

type Foo struct {
	A sql.NullString
	B sql.NullString
}
