// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
)

type NewTable struct {
	Val sql.NullInt32
}

type OldTable struct {
	Val sql.NullInt32
}

type PgTempMigrate struct {
	Val sql.NullInt32
}
