// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

type Bar struct {
	ID uint64
}

type Baz struct {
	ID uint64
}

type Foo struct {
	BarID uint64
	BazID int32
}
