// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
)

type Bar struct {
	A sql.NullString
	C sql.NullString
}

type Baz struct {
	Z sql.NullString
}

type Foo struct {
	A     sql.NullString
	B     sql.NullString
	Group sql.NullString
}
