// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type A struct {
	AID   pgtype.Text
	BIDFk pgtype.Text
}

type B struct {
	BID pgtype.Text
}
