// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1
// source: query.sql

package querytest

import (
	"database/sql"
)

const insertSingleValue = `-- name: InsertSingleValue :copyfrom
INSERT INTO foo (a) VALUES (?)
`

type InsertSingleValueParams struct {
	A sql.NullString
}
