// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package override

import (
	"github.com/sqlc-dev/sqlc-testdata/pkg"
)

type Foo struct {
	Other   string
	Total   int64
	Retyped pkg.CustomType
}
