// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package db

import (
	"database/sql"
)

type Author struct {
	ID     int64
	Name   string
	Rating int64
	Score  uint32
	Bio    sql.NullString
}
