// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
)

type Bar struct {
	A     int32
	Alias sql.NullString
}

type Foo struct {
	A    int32
	Name sql.NullString
}
