// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const updateSet = `-- name: UpdateSet :exec
UPDATE foo SET name = ? WHERE slug = ?
`

type UpdateSetParams struct {
	Name string
	Slug string
}

func (q *Queries) UpdateSet(ctx context.Context, arg UpdateSetParams) error {
	_, err := q.db.ExecContext(ctx, updateSet, arg.Name, arg.Slug)
	return err
}
