// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"github.com/jackc/pgtype"
)

type TestTable struct {
	VBitNull    pgtype.Varbit
	VVarbitNull pgtype.Varbit
	VBit        pgtype.Varbit
	VVarbit     pgtype.Varbit
}
