// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
)

type Author struct {
	ID       int64
	Name     string
	ParentID sql.NullInt64
}
