// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

type Attribute struct {
	ID   int64
	Name string
}

type AttributeValue struct {
	ID        int64
	Val       string
	Attribute int64
}
