// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bar struct {
	ID    int32
	Title pgtype.Text
}

type Foo struct {
	ID int32
}
