// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"

	"github.com/google/uuid"
)

type Foo struct {
	Description sql.NullString
	Bar         uuid.NullUUID
	Baz         uuid.UUID
}
