// Code generated by narsilc. DO NOT EDIT.

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthorRow struct {
	ID   int64       `andurel:"id"`
	Name string      `andurel:"name"`
	Bio  pgtype.Text `andurel:"bio"`
}
