// Code generated by narsilc. DO NOT EDIT.
// source: query.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/mbvlabs/narsilc"
)

const authorPostCounts = `-- name: AuthorPostCounts :many
SELECT a.id, a.name, count(p.id) AS post_count
FROM authors a
LEFT JOIN posts p ON p.author_id = a.id
GROUP BY a.id, a.name
`

type AuthorPostCountsRow struct {
	ID        int64  `andurel:"id"`
	Name      string `andurel:"name"`
	PostCount int64  `andurel:"post_count"`
}

func (q *Queries) AuthorPostCounts[T any](ctx context.Context) ([]T, error) {
	rows, err := q.db.Query(ctx, authorPostCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	var probe T
	_, mapRow := any(&probe).(narsilc.Transformer[AuthorPostCountsRow])
	cols := []string{"id", "name", "post_count"}
	for rows.Next() {
		var item T
		var err error
		if mapRow {
			var scanned AuthorPostCountsRow
			scanned, err = narsilc.Scan[AuthorPostCountsRow](rows, cols)
			if err == nil {
				item, err = narsilc.FromRow[T, AuthorPostCountsRow](scanned)
			}
		} else {
			item, err = narsilc.Scan[T](rows, cols)
		}
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuthors = `-- name: CountAuthors :one
SELECT count(*) FROM authors
`

func (q *Queries) CountAuthors(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (
  name, bio
) VALUES (
  $1, $2
)
RETURNING id, name, bio
`

type CreateAuthorParams struct {
	Name string
	Bio  pgtype.Text
}

func (q *Queries) CreateAuthor[T any](ctx context.Context, arg CreateAuthorParams) (T, error) {
	row := q.db.QueryRow(ctx, createAuthor, arg.Name, arg.Bio)
	return narsilc.Read[T, AuthorRow](row, []string{"id", "name", "bio"})
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAuthor, id)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, bio FROM authors
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAuthor[T any](ctx context.Context, id int64) (T, error) {
	row := q.db.QueryRow(ctx, getAuthor, id)
	return narsilc.Read[T, AuthorRow](row, []string{"id", "name", "bio"})
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, bio FROM authors
ORDER BY name
`

func (q *Queries) ListAuthors[T any](ctx context.Context) ([]T, error) {
	rows, err := q.db.Query(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	var probe T
	_, mapRow := any(&probe).(narsilc.Transformer[AuthorRow])
	cols := []string{"id", "name", "bio"}
	for rows.Next() {
		var item T
		var err error
		if mapRow {
			var scanned AuthorRow
			scanned, err = narsilc.Scan[AuthorRow](rows, cols)
			if err == nil {
				item, err = narsilc.FromRow[T, AuthorRow](scanned)
			}
		} else {
			item, err = narsilc.Scan[T](rows, cols)
		}
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
