// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"

	"github.com/google/uuid"
)

type Author struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

type User struct {
	Sub uuid.UUID
}
