// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ComputedTablesSomething struct {
	ID        pgtype.Int4
	EventType string
	CreatedAt pgtype.Timestamptz
}

type Event struct {
	ID        pgtype.Int4
	EventType string
	CreatedAt pgtype.Timestamptz
}
