// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
	"time"
)

type Notice struct {
	ID        int32
	Cnt       int32
	Status    string
	NoticeAt  sql.NullTime
	CreatedAt time.Time
}
