// Code generated by narsilc. DO NOT EDIT.
// source: query.sql

package querytest

import (
	"context"
	"fmt"
	"strings"
	"time"
)

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, created_at FROM authors
WHERE tenant_id = $1
`

type ListAuthorsRow struct {
	ID        int64
	Name      string
	CreatedAt time.Time
}

func (q *Queries) ListAuthors(ctx context.Context, tenantID int64) *ListAuthorsBuilder {
	return &ListAuthorsBuilder{
		q:        q,
		ctx:      ctx,
		args:     []any{tenantID},
		hasWhere: true,
		dollar:   true,
	}
}

type ListAuthorsBuilder struct {
	q        *Queries
	ctx      context.Context
	args     []any
	conds    []string
	order    string
	limit    *int32
	offset   *int32
	hasWhere bool
	dollar   bool
}

func (b *ListAuthorsBuilder) NameEq(v string) *ListAuthorsBuilder {
	b.args = append(b.args, v)
	b.conds = append(b.conds, fmt.Sprintf(`name = $%d`, len(b.args)))
	return b
}

func (b *ListAuthorsBuilder) NameLike(v string) *ListAuthorsBuilder {
	b.args = append(b.args, v)
	b.conds = append(b.conds, fmt.Sprintf(`name LIKE $%d`, len(b.args)))
	return b
}

func (b *ListAuthorsBuilder) CreatedAtGte(v time.Time) *ListAuthorsBuilder {
	b.args = append(b.args, v)
	b.conds = append(b.conds, fmt.Sprintf(`created_at >= $%d`, len(b.args)))
	return b
}

func (b *ListAuthorsBuilder) CreatedAtLte(v time.Time) *ListAuthorsBuilder {
	b.args = append(b.args, v)
	b.conds = append(b.conds, fmt.Sprintf(`created_at <= $%d`, len(b.args)))
	return b
}

func (b *ListAuthorsBuilder) OrderByNameAsc() *ListAuthorsBuilder {
	b.order = `name ASC`
	return b
}

func (b *ListAuthorsBuilder) OrderByNameDesc() *ListAuthorsBuilder {
	b.order = `name DESC`
	return b
}

func (b *ListAuthorsBuilder) OrderByCreatedAtAsc() *ListAuthorsBuilder {
	b.order = `created_at ASC`
	return b
}

func (b *ListAuthorsBuilder) OrderByCreatedAtDesc() *ListAuthorsBuilder {
	b.order = `created_at DESC`
	return b
}

func (b *ListAuthorsBuilder) OrderByIDAsc() *ListAuthorsBuilder {
	b.order = `id ASC`
	return b
}

func (b *ListAuthorsBuilder) OrderByIDDesc() *ListAuthorsBuilder {
	b.order = `id DESC`
	return b
}

func (b *ListAuthorsBuilder) Limit(n int32) *ListAuthorsBuilder {
	b.limit = &n
	return b
}

func (b *ListAuthorsBuilder) Offset(n int32) *ListAuthorsBuilder {
	b.offset = &n
	return b
}

func (b *ListAuthorsBuilder) build() string {
	query := listAuthors
	if len(b.conds) > 0 {
		if b.hasWhere {
			query += " AND " + strings.Join(b.conds, " AND ")
		} else {
			query += " WHERE " + strings.Join(b.conds, " AND ")
		}
	}
	if b.order != "" {
		query += " ORDER BY " + b.order
	}
	if b.limit != nil {
		b.args = append(b.args, *b.limit)
		if b.dollar {
			query += fmt.Sprintf(" LIMIT $%d", len(b.args))
		} else {
			query += " LIMIT ?"
		}
	}
	if b.offset != nil {
		b.args = append(b.args, *b.offset)
		if b.dollar {
			query += fmt.Sprintf(" OFFSET $%d", len(b.args))
		} else {
			query += " OFFSET ?"
		}
	}
	return query
}

func (b *ListAuthorsBuilder) All() ([]ListAuthorsRow, error) {
	query := b.build()
	rows, err := b.q.db.QueryContext(b.ctx, query, b.args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsRow
	for rows.Next() {
		var i ListAuthorsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
