// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"time"

	"github.com/google/uuid"
)

type TddTest struct {
	TestID    uuid.UUID
	Title     string
	Descr     string
	TsCreated time.Time
	TsUpdated time.Time
}
