// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package db

import (
	"database/sql"
)

type X struct {
	A sql.NullString
	B sql.NullString
}

type Y struct {
	A sql.NullString
	B sql.NullString
}
