// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"github.com/pgvector/pgvector-go"
)

type Item struct {
	ID        int64
	Embedding pgvector.Vector
}
