// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"context"
)

type Querier interface {
	User(ctx context.Context) ([]int64, error)
}

var _ Querier = (*Queries)(nil)
