// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1
// source: query.sql

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InsertValuesParams struct {
	A pgtype.Text
	B pgtype.Int4
}
