// Code generated by narsilc. DO NOT EDIT.

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type AuthorRow struct {
	ID         int64       `andurel:"id"`
	PublicID   uuid.UUID   `andurel:"public_id"`
	ExternalID *uuid.UUID  `andurel:"external_id"`
	Name       string      `andurel:"name"`
	Bio        pgtype.Text `andurel:"bio"`
}
