// Code generated by narsilc. DO NOT EDIT.
// source: query.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/mbvlabs/narsilc"
	"uuid"
)

const authorPostCounts = `-- name: AuthorPostCounts :many
SELECT a.id, a.name, count(p.id) AS post_count
FROM authors a
LEFT JOIN posts p ON p.author_id = a.id
GROUP BY a.id, a.name
`

func (q *Queries) AuthorPostCounts[T any](ctx context.Context) ([]T, error) {
	rows, err := q.db.Query(ctx, authorPostCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	for rows.Next() {
		item, err := narsilc.Scan[T](rows, []string{"id", "name", "post_count"})
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuthors = `-- name: CountAuthors :one
SELECT count(*) FROM authors
`

func (q *Queries) CountAuthors(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (
  public_id, external_id, name, bio
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, public_id, external_id, name, bio
`

type CreateAuthorParams struct {
	PublicID   uuid.UUID
	ExternalID *uuid.UUID
	Name       string
	Bio        pgtype.Text
}

func (q *Queries) CreateAuthor[T any](ctx context.Context, arg CreateAuthorParams) (T, error) {
	row := q.db.QueryRow(ctx, createAuthor,
		arg.PublicID,
		arg.ExternalID,
		arg.Name,
		arg.Bio,
	)
	return narsilc.Scan[T](row, []string{"id", "public_id", "external_id", "name", "bio"})
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAuthor, id)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, public_id, external_id, name, bio FROM authors
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAuthor[T any](ctx context.Context, id int64) (T, error) {
	row := q.db.QueryRow(ctx, getAuthor, id)
	return narsilc.Scan[T](row, []string{"id", "public_id", "external_id", "name", "bio"})
}

const getAuthorByPublicID = `-- name: GetAuthorByPublicID :one
SELECT id, public_id, external_id, name, bio FROM authors
WHERE public_id = $1 LIMIT 1
`

func (q *Queries) GetAuthorByPublicID[T any](ctx context.Context, publicID uuid.UUID) (T, error) {
	row := q.db.QueryRow(ctx, getAuthorByPublicID, publicID)
	return narsilc.Scan[T](row, []string{"id", "public_id", "external_id", "name", "bio"})
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, public_id, external_id, name, bio FROM authors
ORDER BY name
`

func (q *Queries) ListAuthors[T any](ctx context.Context) ([]T, error) {
	rows, err := q.db.Query(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	for rows.Next() {
		item, err := narsilc.Scan[T](rows, []string{"id", "public_id", "external_id", "name", "bio"})
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
