// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

type Bar struct {
	ID int64
}

type Baz struct {
	ID int64
}

type Foo struct {
	BarID int64
	BazID int64
}
