// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"time"
)

type Expiration struct {
	ID        int32
	CreatedAt time.Time
	Expiry    time.Time
}
