// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

type Item struct {
	ItemID int64
}

type Plan struct {
	PlanID int64
}

type PlanItem struct {
	PlanItemID int64
	PlanID     int64
	ItemID     int64
}
