// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
)

type Contact struct {
	Pid          sql.NullString
	Customername sql.NullString
}
