// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
)

type Event struct {
	ID sql.NullInt32
}

type HandledEvent struct {
	LastHandledID sql.NullInt32
	Handler       sql.NullString
}
