// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
)

type SuperUser struct {
	ID          int32
	FirstName   string
	LastName    sql.NullString
	DateOfBirth sql.NullTime
}

type User struct {
	ID       int32
	LastName sql.NullString
	Age      int32
}
