// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Foo struct {
	Bar    string
	Baz    pgtype.Int4
	Bio    pgtype.Int4
	Foobar []int32
}
