// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
)

type Author struct {
	Name string
	Bio  sql.NullString
}

type Person struct {
	FirstName string
}
