// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"time"
)

type User struct {
	ID        int32
	Fname     string
	Lname     string
	Email     string
	EncPasswd string
	CreatedAt time.Time
}
