// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
)

type Author struct {
	ID     int64
	Name   string
	Bio    sql.NullString
	Gender sql.NullInt32
}

type AuthorsName struct {
	Name string
}
