// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

type Calorie struct {
	ID string
}

type Campus struct {
	ID string
}

type ProductMetadatum struct {
	ID string
}

type ProductMetum struct {
	ID string
}

type Student struct {
	ID string
}
