// Code generated by narsilc. DO NOT EDIT.
// source: query.sql

package queries

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/mbvlabs/narsilc"
)

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, created_at FROM authors
WHERE tenant_id = $1
`

func (q *Queries) ListAuthors[T any](ctx context.Context, tenantID int64) *ListAuthorsBuilder[T] {
	return &ListAuthorsBuilder[T]{
		q:        q,
		ctx:      ctx,
		args:     []any{tenantID},
		hasWhere: true,
		dollar:   true,
	}
}

type ListAuthorsBuilder[T any] struct {
	q        *Queries
	ctx      context.Context
	args     []any
	conds    []string
	order    string
	limit    *int32
	offset   *int32
	hasWhere bool
	dollar   bool
}

func (b *ListAuthorsBuilder[T]) NameEq(v string) *ListAuthorsBuilder[T] {
	b.args = append(b.args, v)
	b.conds = append(b.conds, fmt.Sprintf(`name = $%d`, len(b.args)))
	return b
}

func (b *ListAuthorsBuilder[T]) NameLike(v string) *ListAuthorsBuilder[T] {
	b.args = append(b.args, v)
	b.conds = append(b.conds, fmt.Sprintf(`name LIKE $%d`, len(b.args)))
	return b
}

func (b *ListAuthorsBuilder[T]) CreatedAtGte(v time.Time) *ListAuthorsBuilder[T] {
	b.args = append(b.args, v)
	b.conds = append(b.conds, fmt.Sprintf(`created_at >= $%d`, len(b.args)))
	return b
}

func (b *ListAuthorsBuilder[T]) CreatedAtLte(v time.Time) *ListAuthorsBuilder[T] {
	b.args = append(b.args, v)
	b.conds = append(b.conds, fmt.Sprintf(`created_at <= $%d`, len(b.args)))
	return b
}

func (b *ListAuthorsBuilder[T]) OrderByNameAsc() *ListAuthorsBuilder[T] {
	b.order = `name ASC`
	return b
}

func (b *ListAuthorsBuilder[T]) OrderByNameDesc() *ListAuthorsBuilder[T] {
	b.order = `name DESC`
	return b
}

func (b *ListAuthorsBuilder[T]) OrderByCreatedAtAsc() *ListAuthorsBuilder[T] {
	b.order = `created_at ASC`
	return b
}

func (b *ListAuthorsBuilder[T]) OrderByCreatedAtDesc() *ListAuthorsBuilder[T] {
	b.order = `created_at DESC`
	return b
}

func (b *ListAuthorsBuilder[T]) OrderByIDAsc() *ListAuthorsBuilder[T] {
	b.order = `id ASC`
	return b
}

func (b *ListAuthorsBuilder[T]) OrderByIDDesc() *ListAuthorsBuilder[T] {
	b.order = `id DESC`
	return b
}

func (b *ListAuthorsBuilder[T]) Limit(n int32) *ListAuthorsBuilder[T] {
	b.limit = &n
	return b
}

func (b *ListAuthorsBuilder[T]) Offset(n int32) *ListAuthorsBuilder[T] {
	b.offset = &n
	return b
}

func (b *ListAuthorsBuilder[T]) build() string {
	query := listAuthors
	if len(b.conds) > 0 {
		if b.hasWhere {
			query += " AND " + strings.Join(b.conds, " AND ")
		} else {
			query += " WHERE " + strings.Join(b.conds, " AND ")
		}
	}
	if b.order != "" {
		query += " ORDER BY " + b.order
	}
	if b.limit != nil {
		b.args = append(b.args, *b.limit)
		if b.dollar {
			query += fmt.Sprintf(" LIMIT $%d", len(b.args))
		} else {
			query += " LIMIT ?"
		}
	}
	if b.offset != nil {
		b.args = append(b.args, *b.offset)
		if b.dollar {
			query += fmt.Sprintf(" OFFSET $%d", len(b.args))
		} else {
			query += " OFFSET ?"
		}
	}
	return query
}

func (b *ListAuthorsBuilder[T]) All() ([]T, error) {
	query := b.build()
	rows, err := b.q.db.QueryContext(b.ctx, query, b.args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	for rows.Next() {
		item, err := narsilc.Scan[T](rows, []string{"id", "name", "created_at"})
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
