// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
)

type Bar struct {
	ID int32
}

type Foo struct {
	ID    int32
	BarID sql.NullInt32
}
