// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package db

import (
	"database/sql"
)

type Bar struct {
	ColA sql.NullBool
	ColB sql.NullBool
	ColC sql.NullBool
}

type Foo struct {
	ColA bool
	ColB bool
	ColC bool
}
