// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Llc struct {
	PartyID           pgtype.UUID
	Name              string
	LegalName         string
	IncorporationDate pgtype.Timestamp
}

type Organisation struct {
	PartyID   pgtype.UUID
	Name      string
	LegalName string
}

type Party struct {
	PartyID pgtype.UUID
	Name    string
}

type Person struct {
	PartyID   pgtype.UUID
	Name      string
	FirstName string
	LastName  string
}
