// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"database/sql"
)

type User struct {
	ID        int32
	FirstName string
	LastName  sql.NullString
	Age       int32
}
