// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"github.com/google/uuid"
)

type Foo struct {
	ID      uuid.UUID
	OtherID uuid.UUID
}

type Foo1 struct {
	ID      uuid.UUID
	OtherID uuid.UUID
}
