// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetAll(ctx context.Context) ([]int32, error)
}

var _ Querier = (*Queries)(nil)
