// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NewTable struct {
	Val pgtype.Int4
}

type OldTable struct {
	Val pgtype.Int4
}

type PgTempMigrate struct {
	Val pgtype.Int4
}
