// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package primary_key_later

import (
	"database/sql"
)

type Author struct {
	ID   int64
	Name string
	Bio  sql.NullString
}
