// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	FirstName pgtype.Text `json:"FirstName"`
	LastName  pgtype.Text `json:"LastName"`
	Age       pgtype.Int2 `json:"Age"`
}
