// Code generated by sqlc. DO NOT EDIT.

package queries

import (
	"fmt"
	"reflect"
	"strings"
	"sync"
)

type andurelScanner interface {
	Scan(dest ...any) error
}

type andurelLayout struct {
	indexes [][]int
}

var andurelLayoutCache sync.Map // map[andurelLayoutKey]andurelLayout

type andurelLayoutKey struct {
	typ     reflect.Type
	columns string
}

func scanAndurel[T any](s andurelScanner, columns []string) (T, error) {
	var dest T
	ptrs, err := andurelDestPtrs(&dest, columns)
	if err != nil {
		return dest, err
	}
	if err := s.Scan(ptrs...); err != nil {
		return dest, err
	}
	return dest, nil
}

func andurelDestPtrs[T any](dest *T, columns []string) ([]any, error) {
	v := reflect.ValueOf(dest).Elem()
	layout, err := andurelLayoutFor(v.Type(), columns)
	if err != nil {
		return nil, err
	}
	ptrs := make([]any, len(layout.indexes))
	for i, idx := range layout.indexes {
		ptrs[i] = v.FieldByIndex(idx).Addr().Interface()
	}
	return ptrs, nil
}

func andurelLayoutFor(t reflect.Type, columns []string) (andurelLayout, error) {
	key := andurelLayoutKey{typ: t, columns: strings.Join(columns, "\x00")}
	if cached, ok := andurelLayoutCache.Load(key); ok {
		return cached.(andurelLayout), nil
	}

	layout, err := andurelBuildLayout(t, columns)
	if err != nil {
		return andurelLayout{}, err
	}
	andurelLayoutCache.Store(key, layout)
	return layout, nil
}

func andurelBuildLayout(t reflect.Type, columns []string) (andurelLayout, error) {
	if t.Kind() != reflect.Struct {
		return andurelLayout{}, fmt.Errorf("andurel: %s is not a struct", t)
	}

	byCol := make(map[string][]int, t.NumField())
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		tag := f.Tag.Get("andurel")
		if tag == "" || tag == "-" {
			continue
		}
		if _, exists := byCol[tag]; exists {
			return andurelLayout{}, fmt.Errorf("andurel: duplicate tag %q on %s", tag, t)
		}
		byCol[tag] = f.Index
	}

	indexes := make([][]int, len(columns))
	for i, col := range columns {
		idx, ok := byCol[col]
		if !ok {
			return andurelLayout{}, fmt.Errorf("andurel: no field with andurel:%q on %s", col, t)
		}
		indexes[i] = idx
	}
	return andurelLayout{indexes: indexes}, nil
}
