// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package date_and_time_functions

import (
	"database/sql"
)

type Student struct {
	StudentName sql.NullString
	TestScore   sql.NullFloat64
}
