// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

import (
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

type Foo struct {
	A json.RawMessage
	B json.RawMessage
	C pqtype.NullRawMessage
	D pqtype.NullRawMessage
}
