// Code generated by narsilc. DO NOT EDIT.
// versions:
//   narsilc v1.31.1

package querytest

type Bar struct {
	ID   int32
	Name string
}

type Exclusions struct {
	ID   int32
	Name string
}

type MyData struct {
	ID   int32
	Name string
}
